apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zafmwzni
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zafmwzni:9d211f7373d9650b3a8ec8fc44d513c129be0612@sha256:bde531c0c7996b254397784f997538dc31d9b474f105f224ecb010ccf66418c8
          name: container-image
